name: 'ROSA'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  rosa:
    name: 'ROSA'
    runs-on: ubuntu-latest
    environment: production


    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: download ROSA client
      run: |-
            rm -rf $GITHUB_WORKSPACE/bin
            mkdir -p $GITHUB_WORKSPACE/bin
            curl -o rosa.tar.gz https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/rosa/latest/rosa-linux.tar.gz
            tar xvf rosa.tar.gz -C $GITHUB_WORKSPACE/bin
            chmod +x $GITHUB_WORKSPACE/bin/rosa
    - name: test rosa
      run: |-
            $GITHUB_WORKSPACE/bin/rosa --help
